### ISSUE TITLE
Couldn't import card into cloud wallet

### ISSUE THREAD

**Issue by samjsmith** [ampretia/composer-wallet-ibmcos#1]
I had a valid card exported from a freshly started Composer/Fabric system and tried to import it and received an error:

```
$ composer card export --name PeerAdmin@hlfv1

Successfully exported business network card
	Card file: PeerAdmin@hlfv1.card
	Card name: PeerAdmin@hlfv1
$ composer card import -f PeerAdmin@hlfv1.card
Error: Failed to save card: PeerAdmin@hlfv1
Command failed
```
Composer card list reported no cards present:
```
$ composer card list
There are no Business Network Cards available.
```

However I had 3 objects created in my Cloud Object Store:
![image](https://user-images.githubusercontent.com/16335033/36973632-a141b132-206b-11e8-8426-6b785a1d3cd6.png)

Looks like it's missing the `/cards/` portion of the card.

**Comment by mbwhite** [comment]
Issue has been resolved PR #2 

new NPM module has been published.

Thanks @samjsmith
